Other
Cunarefa/Flask_test pull request #1
Opened 2021-04-19 13:47 UTC by Cunarefa

2021-04-19 14:05 UTC, vladysllav requested changes

2021-04-19 14:05 UTC, vladysllav commented on api2/__init__.py
> +    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
Можешь использовать os.getenv, вместо текущей конструкции

2021-04-19 14:05 UTC, vladysllav commented on api2/__init__.py
> +    app.register_blueprint(bp_auth, url_prefix='/auth')
Изменить префикс с auth на api

2021-04-19 14:05 UTC, vladysllav commented on api2/blueprints/__init__.py
> +bp_auth = Blueprint('bp_auth', __name__, template_folder='templates')
Удали темплейт фолдеры

2021-04-19 14:05 UTC, vladysllav commented on api2/blueprints/posts.py
> +    return jsonify(post_schema.dump(posts))
Убери jsonify фласк и так применит его под коробкой

2021-04-19 14:05 UTC, vladysllav commented on api2/blueprints/posts.py
> +from marshmallow import ValidationError
Отлавливай ошибки валидации и корректно их отобрази

2021-04-19 14:05 UTC, vladysllav commented on api2/blueprints/posts.py
>      return jsonify({'message': f'Post with {post_id} id was deleted'})
Статус код нужно использовать 204 при удалении

2021-04-19 14:05 UTC, vladysllav commented on api2/blueprints/posts.py
> +    return make_response(post_schema.dump(post), 201)
Можно просто `return post_schema.dump(post), 201`

2021-04-19 14:05 UTC, vladysllav commented on api2/models/posts.py
> +    inserted_at = db.Column(db.Date, default=datetime.date.today())
Используй DateTime в обоих случаях

2021-04-19 14:12 UTC, vladysllav commented on migrations/versions/ee9fb89358fe_.py
>      sa.Column('username', sa.String(length=100), nullable=False),
password_hash не должен быть нулл

2021-04-19 14:14 UTC, vladysllav commented on api2/__init__.py
>      app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:Actimel13@localhost:5433/avada2'
Все эти данные должны храниться в переменных окружения в .env файле
В свою очередь этот файл должен быть всегда в корне проэкта, а не в папке апликейшна

2021-04-19 14:24 UTC, vladysllav commented on .gitignore
> +__pycache__/
Не забудь добавить еще .pyc файлы

2021-04-19 14:25 UTC, vladysllav commented on .gitignore
> +__pycache__/
Так же удали все файлы кэша который залил, что бы они больше не тригерились гитом удали их из индекса, вот вопрос на стэке почитай, там ответ рабочий
https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

2021-04-20 10:27 UTC, vladysllav commented on api2/blueprints/posts.py
> +    return make_response(f'Post with {post_id} id was deleted', 204)
Тебе не нужен make_response,  же писал что ты можешь просто дикт вернуть и через запятую статус
Если не понимаешь как, погугли

2021-04-20 10:28 UTC, vladysllav commented on migrations/versions/7f67f9795d54_.py
> +    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
Почему снова nullable?

2021-04-20 10:29 UTC, vladysllav commented on migrations/versions/7f67f9795d54_.py
> +    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
У тебя две миграции, нет смысла пладить столько, сделай одну, где пароль сразу будет nullable

2021-04-20 14:56 UTC, Cunarefa commented on migrations/versions/7f67f9795d54_.py
> +    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
Удалил миграцию

2021-04-20 14:56 UTC, Cunarefa commented on api2/blueprints/posts.py
> +    return make_response(f'Post with {post_id} id was deleted', 204)
Исправил

2021-04-21 09:46 UTC, merged